/**
 * Central icon module. Pages/components import icons from here, never
 * directly from `lucide-react` — this keeps the icon set curated and makes
 * it easy to swap a name later without touching call sites everywhere.
 */
export type { LucideIcon } from 'lucide-react';
export {
  LayoutDashboard,
  FolderKanban,
  Building2,
  Columns3,
  GanttChart,
  ListChecks,
  CalendarDays,
  Users,
  Gauge,
  Settings,
  Search,
  Menu,
  X,
  ChevronRight,
  ChevronLeft,
  ChevronsLeft,
  ChevronsRight,
  Plus,
  Trash2,
  Pencil,
  Save,
  Check,
  AlertTriangle,
  ArrowRightLeft,
  ZoomIn,
  ZoomOut,
  Filter,
  Bookmark,
  Clock,
  ClipboardList,
  CircleHelp,
  Compass,
  Sparkles,
  ArrowLeft,
  KeyRound,
  Network,
  Inbox,
  Megaphone,
} from 'lucide-react';
