export const DEFAULT_ALLOWED_TOOLS = [
  "Read",
  "Write",
  "Edit",
  "MultiEdit",
  "Glob",
  "Grep",
  "LS",
  "TodoWrite",
  "Agent",
  "Bash(git status:*)",
  "Bash(git diff:*)",
  "Bash(git log:*)",
  "Bash(git show:*)",
  "Bash(git rev-parse:*)",
  "Bash(git branch --show-current)",
  "Bash(git merge-base:*)",
  "Bash(npx vitest:*)",
  "Bash(npm run test:scheduler:*)",
  "Bash(npm run typecheck:*)",
  "Bash(npm run check:browser-regression:*)",
  "Bash(node scripts/check-openwiki-links.mjs:*)",
  "Bash(node scripts/browser-check-bin-drag.mjs:*)",
  "Bash(node scripts/browser-check-bin-split.mjs:*)",
  "Bash(node scripts/browser-check-date-hardening.mjs:*)",
  "Bash(node scripts/browser-check-onboarding.mjs:*)",
  "Bash(node scripts/browser-check-placement.mjs:*)",
  "Bash(node scripts/browser-check-savetask-multiblock.mjs:*)",
  "Bash(node scripts/browser-check-status-semantics.mjs:*)",
  "Bash(node scripts/browser-check-tab-sync.mjs:*)",
  "Bash(node scripts/run-browser-regression.mjs:*)",
  "Bash(pwd)",
];

export const DEFAULT_DISALLOWED_TOOLS = [
  "Bash(codex:*)",
  "Bash(npx codex:*)",
  "Bash(npx @openai/codex:*)",
  "Bash(npx --yes @openai/codex:*)",
  "Bash(npm exec:*)",
  "Bash(npm x:*)",
  "Bash(node -e:*)",
  "Bash(node --eval:*)",
  "Bash(find:*)",
  "Bash(rg --pre:*)",
];

export const REVIEWER_ALLOWED_TOOLS = [
  "Read",
  "Glob",
  "Grep",
  "LS",
];
